FROM python:3.11-bookworm

# Create a link so python appears in the same place as the RPi
RUN ln -s /usr/local/bin/python /usr/bin/python \
    && mkdir /app

COPY requirements.txt /tmp/requirements.txt

# Create user and Prerequisites
RUN useradd -m -s /bin/bash user \
    && echo "user:password" | chpasswd

USER user

RUN pip install --upgrade pip \
    && pip install -r /tmp/requirements.txt


