services:
  stable-virtual-camera:
    image: stable-virtual-camera:1.0.1
    container_name: stable-virtual-camera
    stdin_open: true
    tty: true
    user: user
    working_dir: /home/user/stable-virtual-camera
    command: python demo_gr.py --no-share
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]