version: '3.8'

services:
  stable-virtual-camera-build:
    image: stable-virtual-camera:build
    container_name: stable-virtual-camera-build
    stdin_open: true
    tty: true
    command: tail -F /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  stable-virtual-camera:
    image: stable-virtual-camera:1.0.0
    container_name: stable-virtual-camera
#    environment:
#      - GRADIO_SERVER_NAME="localhost"
#      - GRADIO_SERVER_PORT=8080
    ports:
      - 7860:7860
    stdin_open: true
    tty: true
    user: user
    working_dir: /home/user/stable-virtual-camera
    command: python demo_gr.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]