version: '3.8'

services:
  ansible-controller:
    image: ansible-controller:1.0.0
    container_name: ansible_controller
    volumes:
      - ./controller:/controller
    working_dir: /ansible
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  ansible-node:
    image: ansible-node:1.0.0
    container_name: ansible_node
    stdin_open: true
    tty: true


