when:
  - event: push

steps:
  - name: test
    image: python:3.11-bookworm
    when:
      - path: 'solar-controlar/**'
    commands:
      - echo "Testing ........."
      - cd solar-controlar
      - python -m unittest discover tests
