when:
  - event: push

steps:
  - name: test
    image: python:3.11-bookworm
    when:
      - path:
          include:
           - solar-controlar/**
           - .woodpecker/solar-controlar.yaml
    commands:
      - echo "Testing ........."
      - cd solar-controlar
      - python -m unittest discover tests
