when:
  - event: push
  - path: 'solar-controlar/**'

steps:
  - name: test
    image: python:3.11-bookworm
    commands:
      - echo "Testing ........."
      - cd solar-controlar
      - python -m unittest discover tests
